### ISSUE TITLE
Getting error:  Could not find entry file: /index.html ???

### ISSUE THREAD

**Issue by weaver543** [dferber90/githubbox#10] opened 2022-02-15 00:37 UTC
For some reason, some repos give me the following error (inconsistently I think):

`Could not find entry file: /index.html. You can specify one in package.json by defining a `main` property.
`

The error doesn't make sense because other repos that work don't have the index.html or main property specified.  

Thoughts?

**Comment by weaver543** [comment] 2022-02-15 09:37
As an example, the following repo works with githubbox, however when I forked it and try githubbox on it, I get that error message (see attached)
https://github.com/gopinav/React-Tutorials/tree/master/React%20Hooks/reducer-hook

![githubbox_error](https://user-images.githubusercontent.com/8516855/154034565-bb85a978-5e5b-4750-9a63-5fe11d6bd2cb.jpg)

**Comment by dferber90** [comment] 2022-02-15 13:51
This is unrelated to githubbox. githubbox is pretty much only a redirect to codesandbox.

The issue you're seeing is related to codesandbox itself (and might not be an issue but intended functionality).

I suspect that things are working as intended. For some of those repos, codesandbox might know how to run them, while it does not know how to run others. This could be due to the applications being nested in subfolders, monorepos and so on.

There's nothing we can do on the githubbox side, so I'll close this. Hope that brought some clarity :)

**Closed by dferber90** 2022-02-15 13:51 UTC
